spring:
  application:
    name: sublite-core

  datasource:
    url: jdbc:postgresql://localhost:5432/sublite
    username: sublite
    password: sublite

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    schemas: shared,subscription,billing
    default-schema: shared

sublite:
  billing:
    scheduler:
      interval: PT1M
    retry:
      base-interval: P1D
      max-attempts: 3
